### ISSUE TITLE
Unexpected diff image output

### ISSUE THREAD

**Issue by ilionic** [segmentio/niffy#3]
**What needs to get done?**

While testing landing page with quite large height ( > 3000px ) running multiple tests with different `scrollTo` values. Diff image produced by the first test is correct, while second one is not. Tried to add extra `.wait()` but it didn't help.
( see produced output images below )

**Why does it need to get done?**

Expect to have visual diff working correctly.

**How do I do it?**

```
  describe('/Landing', function () {
    it('Homepage1', function* () {
      yield niffy.test('/?test=1', function* (nightmare) {
        yield nightmare.scrollTo(800, 0);
      });
    })
    it('Homepage2', function* () {
      yield niffy.test('/?test=2', function* (nightmare) {
        yield nightmare.scrollTo(2000, 0);
      });
    })
  });
```

Example test1 ( correct )
--------

*base*
![base](https://cloud.githubusercontent.com/assets/1027871/25565494/877a31f4-2dd0-11e7-9874-43dc4a74549b.png)
*diff*
![diff](https://cloud.githubusercontent.com/assets/1027871/25565495/877b2ea6-2dd0-11e7-949f-0d831a245f85.png)
*test*
![test](https://cloud.githubusercontent.com/assets/1027871/25565496/877b95e4-2dd0-11e7-9bee-64f4faf84d96.png)

-------
Example test2 ( wrong )
--------
*base*
![base](https://cloud.githubusercontent.com/assets/1027871/25565511/cd5faf1e-2dd0-11e7-988e-30f7094534b5.png)
**diff** ( looks chopped )
![diff](https://cloud.githubusercontent.com/assets/1027871/25565512/cd61371c-2dd0-11e7-92e3-705dfe3c6402.png)
*test*
![test](https://cloud.githubusercontent.com/assets/1027871/25565513/cd624eae-2dd0-11e7-8d31-c569e1f267d5.png)

**Comment by reinpk** [comment]
thanks for submitting the issue! unfortunately i haven't been able to reproduce the issue on any sites i've tested (google, github, bridebook, segment). is there a public site you could demonstrate the failure on? sorry/thanks!

**Comment by ilionic** [comment]
@reinpk here is it, full test source https://gist.github.com/ilionic/0f7b646268998384ef162fe28285fcf0
Extra observation - if I add one more test, first and second are fine but diff of the last one always fails.
Thanks for looking into it.

**Comment by reinpk** [comment]
thanks @ilionic — i gave that a test run locally and got the following output:

![diff](https://cloud.githubusercontent.com/assets/658545/25582124/5c7ee9a2-2e40-11e7-8bc5-07a2a8b0227a.png)

it's working very repeatably for me, unfortunately. what sort of machine are you running on?

also, you want to try moving the `after` method outside of the `describe` to be at the same nesting level as `before`, but I tried both and both worked for me here.

**Comment by ilionic** [comment]
Indeed it's my machine specific bug ( MBP 2012 ) maybe some deps need to be updated..
Tried it to run it on another one ( MBP 2016 ) and all works fine.
I will close this issue then, thank you.

**Comment by ilionic** [comment]
Actually newer MBP also has similar issue ( last test diff is randomly breaking ) if there are 5 - 6 tests with different scroll positions. Will try later somewhere on CI / linux

**Comment by AshCoolman** [comment]
I also get a strange diff when I set any viewport size. The source images look fine, but the diff seems , half rendered and with low opacity (as above)
