### ISSUE TITLE
Use as an npm module?

### ISSUE THREAD

**Issue by oftenfrequent** [segmentio/niffy#6]
I'm a bit new to regression testing so forgive me if this question is an obvious one, however, I spent a good amount of time attempting to pull niffy into a project as an npm module and couldn't get the test spec to run properly.

Is regression testing supposed to exist as a stand alone project, built specifically for its use case? I was expecting to add it to the test specs of our current app build so that during significant updates we can run regression testing to make sure things did not change too much (or only the right things changed).

I have npm installed the proper modules - mocha, chai, niffy (and nightmare for good measure), used the test section of Makefile, and copied code I edited (and proved worked) from `/test/index.js`. The test spec will run but the tests just pass automatically and the electron window will not pop up. Any ideas here?

**Comment by Rup1** [comment]
@k23Burke Did you remove the generators? If not, you need to make sure to install and include `co-mocha` as a dependency. Without it, mocha doesn't have support for Javascript generators

**Comment by oftenfrequent** [comment]
I was using co-mocha but somehow missed out on the `mocha.opts` file. Your comment made sure I went back for another look. Thanks for the help @Rup1. You win today
